### PR TITLE
add peek function

### PR DESCRIPTION
**Pull request by xiezhenye**
We need to peek at the queue but not ack the message before ensure the message is correctly handled.

### CODE REVIEW

**Comment by mreiferson** [comment]
Thanks @xiezhenye. Could you describe this use case in more detail please?

**Comment by xiezhenye** [comment]
We use go-diskqueue to persist events in order to prevent lose event when process crash. If we read an event from the ReadChan and crash before the event handled, the event will lose. I added an Peek function that only read the first event but not ack it. Now, I can Peek an event, handle it, and use ReadChan to ack at to ensure the events be handled.

**Comment by mreiferson** [comment]
I think I follow, but would it be more consistent with the existing interface to expose `PeekChan() <-chan []byte` instead?

**Comment by xiezhenye** [comment]
Peek operation always returns the first message, not looks like reading something from a stream as a chan. 
Using `Peek() interface{}` instead of `PeekChan() <-chan` can also prevent misuse. For example, 
```go
for msg := range q.PeekChan() {
 ...
}
```
is an infinite loop.

**Comment by ploxiln** [comment]
I think that the concern is that with this interface:

```go
func (d *diskQueue) Peek() []byte {
	return <-d.peekChan
}
```

there is no way to avoid blocking, like:

```go
select {
	case msg := <- peekChan:
		return msg
	default:
		return nil
}
```

and no way to mix with other conditions, like:

```go
select {
	case msg := <- peekChan:
		return msg
	case <- exitChan:
		return nil
}
```

**Comment by xiezhenye** [comment]
I changed the code just like Depth do.

**Comment by StoneYunZhao** [comment]
I need this feature too.

**Comment by mreiferson** [comment]
we'll probably end up taking #24, closing, but thanks for the PR.

**Pull request closed without merging**
