### PR TITLE
fix blocking Depth() call on the closed queue

### PR DESCRIPTION
**Pull request by mgurevin**

### CODE REVIEW

**Comment by ploxiln** [comment]
Looks like a fixup for #11, thanks.

**Comment by ploxiln** [comment]
In what program did you observe this problem, btw? Was it nsqd or something else?

**Comment by mgurevin** [comment]
I'm using this package in my program to have disk backed channels.

I think the depth method would be better if it returns the real value from the metadata file when the queue is closed. Maybe the last value of the depth before the queue closing can also be used.

**Comment by ploxiln** [comment]
Yeah ... maybe something like this, in addition to your fix, would be sufficient:

```diff
--- a/diskqueue.go
+++ b/diskqueue.go
@@ -138,7 +138,12 @@ func New(name string, dataPath string, maxBytesPerFile int64,
 
 // Depth returns the depth of the queue
 func (d *diskQueue) Depth() int64 {
-       return <-d.depthChan
+       depth, ok := <-d.depthChan
+       if !ok {
+               // ioLoop exited
+               depth = d.depth
+       }
+       return depth
 }
```

**Comment by mgurevin** [comment]
That was my first attempt too. I prefer this if it's also ok for you.

**Comment by ploxiln** [comment]
Yeah that seems fine to me. You want to add that bit to this PR?

**Pull request merged**
